apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvrocks-pv-service-a
spec:
  capacity:
    storage: 400Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /kvrocks-a/var/lib/kvrocks
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvrocks-pvc-service-a
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: manual

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvrocks-service-a
  labels:
    app: kvrocks-service-a
spec:
  selector:
    matchLabels:
      app: kvrocks-service-a
  template:
    metadata:
      labels:
        app: kvrocks-service-a
    spec:
      initContainers:
        - name: config-setup
          image: alpine
          command: ['sh', '-c', 'cp /etc/kvrocks/kvrocks.conf /var/lib/kvrocks/kvrocks.conf']
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kvrocks
            - name: kvrocks-data
              mountPath: /var/lib/kvrocks
      containers:
        - name: kvrocks
          image: apache/kvrocks:latest
          ports:
            - containerPort: 6666
          volumeMounts:
            - mountPath: /var/lib/kvrocks
              name: kvrocks-data
      volumes:
        - name: config-volume
          configMap:
            name: kvrocks-config
        - name: kvrocks-data
          persistentVolumeClaim:
            claimName: kvrocks-pvc-service-a

---

apiVersion: v1
kind: Service
metadata:
  name: kvrocks-service-a
spec:
  type: NodePort
  selector:
    app: kvrocks-service-a
  ports:
    - port: 6666
      targetPort: 6666
      nodePort: 30666